/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as CfaRouteImport } from './routes/cfa'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAnnouncementsRouteImport } from './routes/admin/announcements'
import { Route as AdminCoursesRouteImport } from './routes/admin/courses'
import { Route as AdminCustomPagesRouteImport } from './routes/admin/custom-pages'
import { Route as AdminHistoryRouteImport } from './routes/admin/history'
import { Route as AdminLeadsRouteImport } from './routes/admin/leads'
import { Route as AdminMediaRouteImport } from './routes/admin/media'
import { Route as AdminNavigationRouteImport } from './routes/admin/navigation'
import { Route as AdminPagesRouteImport } from './routes/admin/pages'
import { Route as AdminSeoRouteImport } from './routes/admin/seo'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminTestimonialsRouteImport } from './routes/admin/testimonials'
import { Route as AdminTrackingRouteImport } from './routes/admin/tracking'
import { Route as AdminUsersRouteImport } from './routes/admin/users'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const CfaRoute = CfaRouteImport.update({
  id: '/cfa',
  path: '/cfa',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnnouncementsRoute = AdminAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCoursesRoute = AdminCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomPagesRoute = AdminCustomPagesRouteImport.update({
  id: '/custom-pages',
  path: '/custom-pages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHistoryRoute = AdminHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNavigationRoute = AdminNavigationRouteImport.update({
  id: '/navigation',
  path: '/navigation',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPagesRoute = AdminPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSeoRoute = AdminSeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTestimonialsRoute = AdminTestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTrackingRoute = AdminTrackingRouteImport.update({
  id: '/tracking',
  path: '/tracking',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/cfa': typeof CfaRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/resources': typeof ResourcesRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/custom-pages': typeof AdminCustomPagesRoute
  '/admin/history': typeof AdminHistoryRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/navigation': typeof AdminNavigationRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/tracking': typeof AdminTrackingRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/admin-login': typeof AdminLoginRoute
  '/cfa': typeof CfaRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/resources': typeof ResourcesRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/custom-pages': typeof AdminCustomPagesRoute
  '/admin/history': typeof AdminHistoryRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/navigation': typeof AdminNavigationRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/tracking': typeof AdminTrackingRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/cfa': typeof CfaRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/resources': typeof ResourcesRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/custom-pages': typeof AdminCustomPagesRoute
  '/admin/history': typeof AdminHistoryRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/navigation': typeof AdminNavigationRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/tracking': typeof AdminTrackingRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/about'
    | '/admin'
    | '/admin-login'
    | '/cfa'
    | '/contact'
    | '/courses'
    | '/resources'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/admin/announcements'
    | '/admin/courses'
    | '/admin/custom-pages'
    | '/admin/history'
    | '/admin/leads'
    | '/admin/media'
    | '/admin/navigation'
    | '/admin/pages'
    | '/admin/seo'
    | '/admin/settings'
    | '/admin/testimonials'
    | '/admin/tracking'
    | '/admin/users'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/about'
    | '/admin-login'
    | '/cfa'
    | '/contact'
    | '/courses'
    | '/resources'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/admin/announcements'
    | '/admin/courses'
    | '/admin/custom-pages'
    | '/admin/history'
    | '/admin/leads'
    | '/admin/media'
    | '/admin/navigation'
    | '/admin/pages'
    | '/admin/seo'
    | '/admin/settings'
    | '/admin/testimonials'
    | '/admin/tracking'
    | '/admin/users'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/about'
    | '/admin'
    | '/admin-login'
    | '/cfa'
    | '/contact'
    | '/courses'
    | '/resources'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/admin/announcements'
    | '/admin/courses'
    | '/admin/custom-pages'
    | '/admin/history'
    | '/admin/leads'
    | '/admin/media'
    | '/admin/navigation'
    | '/admin/pages'
    | '/admin/seo'
    | '/admin/settings'
    | '/admin/testimonials'
    | '/admin/tracking'
    | '/admin/users'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  CfaRoute: typeof CfaRoute
  ContactRoute: typeof ContactRoute
  CoursesRoute: typeof CoursesRoute
  ResourcesRoute: typeof ResourcesRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cfa': {
      id: '/cfa'
      path: '/cfa'
      fullPath: '/cfa'
      preLoaderRoute: typeof CfaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/announcements': {
      id: '/admin/announcements'
      path: '/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AdminAnnouncementsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/courses': {
      id: '/admin/courses'
      path: '/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AdminCoursesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/custom-pages': {
      id: '/admin/custom-pages'
      path: '/custom-pages'
      fullPath: '/admin/custom-pages'
      preLoaderRoute: typeof AdminCustomPagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/history': {
      id: '/admin/history'
      path: '/history'
      fullPath: '/admin/history'
      preLoaderRoute: typeof AdminHistoryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/navigation': {
      id: '/admin/navigation'
      path: '/navigation'
      fullPath: '/admin/navigation'
      preLoaderRoute: typeof AdminNavigationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pages': {
      id: '/admin/pages'
      path: '/pages'
      fullPath: '/admin/pages'
      preLoaderRoute: typeof AdminPagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/seo': {
      id: '/admin/seo'
      path: '/seo'
      fullPath: '/admin/seo'
      preLoaderRoute: typeof AdminSeoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/testimonials': {
      id: '/admin/testimonials'
      path: '/testimonials'
      fullPath: '/admin/testimonials'
      preLoaderRoute: typeof AdminTestimonialsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tracking': {
      id: '/admin/tracking'
      path: '/tracking'
      fullPath: '/admin/tracking'
      preLoaderRoute: typeof AdminTrackingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnnouncementsRoute: typeof AdminAnnouncementsRoute
  AdminCoursesRoute: typeof AdminCoursesRoute
  AdminCustomPagesRoute: typeof AdminCustomPagesRoute
  AdminHistoryRoute: typeof AdminHistoryRoute
  AdminLeadsRoute: typeof AdminLeadsRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminNavigationRoute: typeof AdminNavigationRoute
  AdminPagesRoute: typeof AdminPagesRoute
  AdminSeoRoute: typeof AdminSeoRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTestimonialsRoute: typeof AdminTestimonialsRoute
  AdminTrackingRoute: typeof AdminTrackingRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnnouncementsRoute: AdminAnnouncementsRoute,
  AdminCoursesRoute: AdminCoursesRoute,
  AdminCustomPagesRoute: AdminCustomPagesRoute,
  AdminHistoryRoute: AdminHistoryRoute,
  AdminLeadsRoute: AdminLeadsRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminNavigationRoute: AdminNavigationRoute,
  AdminPagesRoute: AdminPagesRoute,
  AdminSeoRoute: AdminSeoRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTestimonialsRoute: AdminTestimonialsRoute,
  AdminTrackingRoute: AdminTrackingRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  CfaRoute: CfaRoute,
  ContactRoute: ContactRoute,
  CoursesRoute: CoursesRoute,
  ResourcesRoute: ResourcesRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
